name: Deploy pivotapi

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
        # - uses: actions/checkout@main
        - uses: actions/checkout@v2

        - name: Deploy to production
          uses: appleboy/ssh-action@master
          with:
            username: pivotapi
            host: 142.93.244.116
            password: ${{ secrets.SSH_PASSWORD }}
            script: 'cd /var/www/pivotapi.com && .github/deployment/deploy.sh'
